version: "3.7"
services:
    nginx:
        container_name: nginx-boilerplate
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/src
            - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
            - ./ssl_cert.cert:/ssl/cert.cert
            - ./ssl_priv.key:/ssl/priv.key
        networks:
            - network-boilerplate
    php:
        build: ./php
        container_name: php-boilerplate
        volumes:
            - ./src:/src
        networks:
            - network-boilerplate
networks:
  network-boilerplate:
